deploy-demo:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/gauntlet_demo_key.pem
    - chmod 600 ~/gauntlet_demo_key.pem
    - ssh -T -o StrictHostKeyChecking=no -i ~/gauntlet_demo_key.pem ec2-user@"$DEPLOY_SERVER_IP" /home/ec2-user/gauntlet/deploy-demo.sh
  only:
    - demo
