# Generated by Django 4.1.9 on 2023-07-08 21:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MatchRound",
            new_name="Round",
        ),
    ]
