# Generated by Django 4.1.9 on 2023-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_rename_matchround_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="winner",
        ),
        migrations.AddField(
            model_name="match",
            name="round_scores",
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name="Round",
        ),
    ]
