# Generated by Django 4.1.9 on 2023-11-01 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0005_alter_plannedtournament_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedtournament",
            name="players",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
