# Generated by Django 4.1.9 on 2023-11-01 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0006_alter_plannedtournament_players"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlannedTournament",
            new_name="Tournament",
        ),
    ]
