# Generated by Django 4.1.9 on 2023-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0007_rename_plannedtournament_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
