# Generated by Django 4.1.9 on 2023-11-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0009_tournament_state_plannedmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedmatch",
            name="tournament",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="matches.tournament"),
        ),
    ]
