# Generated by Django 4.1.9 on 2024-05-31 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0010_plannedmatch_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedmatch",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_matches",
                to="matches.tournament",
            ),
        ),
    ]
